---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: yes

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes

- name: Copy custom Nginx config (if you have one)
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Reload Nginx
  become: yes

- name: Ensure Nginx is listening
  ufw:
    rule: allow
    name: "Nginx Full"
  become: yes

# Handlers
- name: Reload Nginx
  service:
    name: nginx
    state: reloaded
  become: yes
