---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Upgrade all packages
  apt:
    upgrade: dist
  become: yes

- name: Install useful utilities
  apt:
    name:
      - vim
      - git
      - curl
      - ufw
      - fail2ban
    state: present
  become: yes

- name: Enable and start UFW (Uncomplicated Firewall)
  ufw:
    state: enabled
    policy: deny
  become: yes

- name: Allow SSH through UFW
  ufw:
    rule: allow
    name: OpenSSH
  become: yes

- name: Ensure fail2ban is enabled and running
  service:
    name: fail2ban
    state: started
    enabled: yes
  become: yes
