name: Deploy Node.js App

on:
  push:
    branches:
      - main
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # (Optional) Build step if you really need packaging
      # - name: Build App
      #   run: |
      #     chmod +x ./build.sh
      #     ./build.sh

      - name: Setup SSH key and inventory
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > id_rsa.pem
          chmod 600 id_rsa.pem

          cat > inventory.ini <<EOL
          [app]
          ${{ secrets.ProductionHost }} ansible_user=${{ secrets.EC2_USER }}
          EOL

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i inventory.ini Ansible-conf/node_service.yml \
            --private-key id_rsa.pem \
            -u ${{ secrets.EC2_USER }} \
            --tags app
